INSERT INTO fundraise_statuses(status) VALUES
('ACTIVE'),
('DONE'),
('POSTPONED'),
('CANCELLED'),
('TRANSFERRED')
ON CONFLICT DO NOTHING ;

INSERT INTO posts(post) VALUES
('NP')
ON CONFLICT DO NOTHING;
