version: '3.7'

services:
  # Go Application
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: one_help_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# Named volumes for persisting PostgreSQL data
volumes:
  postgres_data:
